---
title: Move38
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@move38.com
description: 'Carefully crafted, self-aware, tabletop games.

'
baseurl: ''
url: http://move38.com
twitter_username: jonathanbobrow
github_username: jbobrow
markdown: kramdown
