---
title: Move38
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
name: Move38
author:
  name: Move38
  facebook: your-id
  twitter: your-id
  github: your-id
  linkedin: your-id
  medium: your-id
  tumblr: your-id
  email: info@move38.com
google-analytics:
  id: UA-84685529-1
disqus:
  id: move38
url: localhost:4000
baseurl: ''
permalink: "/:title/"
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  imput: GFM
nav:
- name: Blog
  url: "/archive"
- name: About
  url: "/about"
- name: Tags
  url: "/tags"
sass:
  sass_dir: _sass
  style: :compressed
gems:
- jekyll-seo-tag
- jekyll-paginate
exclude:
- vendor
